# Generated by Django 4.2.11 on 2024-05-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0002_alter_eatery_user_alter_group_user_alter_reply_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="open_flag",
            field=models.BooleanField(db_column="open_flag", default=False),
        ),
    ]
