# Generated by Django 4.2.11 on 2024-05-24 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_group_open_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="EateryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(db_column="type_name", max_length=20)),
                ("image_url", models.CharField(db_column="image_url", max_length=255)),
            ],
            options={
                "db_table": "eatery_type",
            },
        ),
        migrations.AlterField(
            model_name="eatery",
            name="eatery_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="website.eaterytype",
            ),
        ),
    ]
