# Generated by Django 4.2.11 on 2024-05-25 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0004_eaterytype_alter_eatery_eatery_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eatery",
            name="eatery_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eatery",
                to="website.eaterytype",
            ),
        ),
        migrations.AlterField(
            model_name="eatery",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eatery",
                to="website.group",
            ),
        ),
        migrations.AlterField(
            model_name="eatery",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eatery",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
