# Generated by Django 4.2.11 on 2024-05-30 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0005_alter_eatery_eatery_type_alter_eatery_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="eatery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply",
                to="website.eatery",
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
