# Generated by Django 3.2.5 on 2022-10-07 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eatery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eatery_name', models.CharField(db_column='eatery_name', max_length=30)),
                ('eatery_type', models.CharField(db_column='eatery_type', max_length=10)),
                ('image', models.ImageField(null=True, upload_to='eatery_image/')),
                ('crawling_image', models.CharField(db_column='crawling_image', max_length=128, null=True)),
                ('eatery_real_location', models.CharField(db_column='eatery_real_location', default='', max_length=128)),
                ('eatery_location', models.CharField(db_column='eatery_location', max_length=128)),
                ('comment', models.TextField(db_column='comment', default='', null=True)),
            ],
            options={
                'db_table': 'enjo_eatery',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(db_column='userid', max_length=50, unique=True)),
                ('password', models.CharField(db_column='password', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(db_column='reply', default='', null=True)),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatery.eatery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatery.user')),
            ],
            options={
                'db_table': 'enjo_reply',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_column='group', max_length=50)),
                ('group_comment', models.TextField(db_column='group_comment', default='', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatery.user')),
            ],
            options={
                'db_table': 'enjo_group',
            },
        ),
        migrations.AddField(
            model_name='eatery',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatery.group'),
        ),
        migrations.AddField(
            model_name='eatery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatery.user'),
        ),
    ]
