# Generated by Django 3.2.5 on 2022-10-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0003_reply_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='location',
            field=models.CharField(db_column='location', default='', max_length=50),
        ),
    ]
