# Generated by Django 3.2.5 on 2022-10-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0004_group_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='location',
            new_name='group_location',
        ),
    ]
